---
title: "Laboratorio 1"
author: "Andrea Reyes"
date: "8/15/2021"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ----- Problema 1 -----

Librerias:
```{r}
library(readxl)
library(tidyverse)
library(dplyr)
library(xlsx)
```


Cargar archivos excel:
```{r}
entrega1 <- read_excel("data/01-2018.xlsx")
entrega2 <- read_excel("data/02-2018.xlsx")
entrega3 <- read_excel("data/03-2018.xlsx")
entrega4 <- read_excel("data/04-2018.xlsx")
entrega5 <- read_excel("data/05-2018.xlsx")
entrega6 <- read_excel("data/06-2018.xlsx")
entrega7 <- read_excel("data/07-2018.xlsx")
entrega8 <- read_excel("data/08-2018.xlsx")
entrega9 <- read_excel("data/09-2018.xlsx")
entrega10 <- read_excel("data/10-2018.xlsx")
entrega11 <- read_excel("data/11-2018.xlsx")
```


Unificar todos los archivos:
```{r}
entregas <- bind_rows(entrega1, entrega2, entrega3, entrega4, entrega5, entrega6, entrega7, entrega8, entrega9, entrega10, entrega11, .id = "FECHA")
head(entregas)
```


Columna fecha:
```{r}
entregas$FECHA <- paste(entregas$FECHA, "- 2018")
head(entregas)
```


Eliminar columnas innecesarias:
```{r}
entregas <- subset(entregas, select = -c(TIPO, ...10) )
head(entregas)
```


Exportar archivo excel:
```{r}
write.xlsx(entregas, "entragasEmbotelladora.xlsx")
```

- El .xlsx se encuentra en la carpeta principal (laboratorio1)


## ----- Problema 2 -----

Crear lista de vectores:
```{r}
listaVectores <- function(n){
  v1 = sample(1:50, size = n, replace = FALSE)
  v2 = sample(1:20, size = n, replace = FALSE)
  v3 = sample(1:80, size = n, replace = FALSE)
  
  vectores <- list(v1, v2, v3)
  return(vectores)
}

vectores <- listaVectores(12)
```


Encontrar la moda de cada vector:
```{r}
lapply(vectores, mean)
```



## ----- Problema 3 -----

Librerias:
```{r}
library(readr)
```


Leer archivo de la sat:
```{r}
textFileSat <- "sat/INE_PARQUE_VEHICULAR_080119.txt"

parqueVehicular <- read_delim(textFileSat, delim = "|")
satVPdf <- data.frame(parqueVehicular)

```


Show:
```{r}
head(satVPdf)
```







